api:
  rate_limits:
    llm_requests_per_minute: 10
    market_data_requests_per_minute: 60
  timeouts:
    llm_timeout_seconds: 30
    market_data_timeout_seconds: 10
application:
  logging:
    backup_count: 5
    file: enhanced_trading.log
    level: INFO
    max_size_mb: 100
  risk:
    blue_chip:
      aggressive:
        max_stocks: 5
        position_limit: 0.25
        stop_loss: 0.15
      conservative:
        max_stocks: 8
        position_limit: 0.25
        stop_loss: 0.15
      moderate:
        max_stocks: 6
        position_limit: 0.25
        stop_loss: 0.15
    default_tolerance: moderate
    max_position_size: 0.1
    micro_cap:
      aggressive:
        max_stocks: 8
        position_limit: 0.25
        stop_loss: 0.15
      conservative:
        max_stocks: 15
        position_limit: 0.25
        stop_loss: 0.15
      moderate:
        max_stocks: 12
        position_limit: 0.25
        stop_loss: 0.15
data:
  automation_dir: automation_data
  base_dir: data
  blue_chip_dir: data_blue_chip
  micro_cap_dir: data_micro_cap
  small_cap_dir: data_small_cap
database:
  host: fhsws001.ksfraser.com
  port: 3306
  username: stocks
  password: stocks
  pool:
    max_connections: 10
    pool_name: trading_pool
    pool_reset_session: true
  legacy:
    database: stock_market_2
    description: Alias for master database (backward compatibility)
  master:
    database: stock_market_2
    description: Master database for all enhanced features, analytics, and web UI
    purpose: enhanced_features
    tables:
    - portfolios_blue_chip
    - portfolios_small_cap
    - portfolios_mid_cap
    - portfolios_large_cap
    - trades_blue_chip
    - trades_small_cap
    - trades_mid_cap
    - trades_large_cap
    - portfolio_performance
    - risk_metrics
    - market_analysis
    - llm_interactions
    - trading_sessions
    - automation_logs
    - user_preferences
    - dashboard_configs
    - alerts_notifications
    - backtesting_results
    - strategy_configurations
    - market_sentiment
  micro_cap:
    database: stock_market_micro_cap_trading
    description: CSV-mirrored data only - original trading_script.py functionality
    purpose: csv_mirror
    tables:
    - portfolio_data
    - trade_log
    - historical_prices
  password: stocks
  pool:
    max_connections: 10
    pool_name: trading_pool
    pool_reset_session: true
  port: 3306
  username: stocks
web_ui:
  auto_launch: false
  document_root: web_ui
  enabled: true
  host: localhost
  php_server: true
  port: 8080
