api:
  rate_limits:
    llm_requests_per_minute: 10
    market_data_requests_per_minute: 60
  timeouts:
    llm_timeout_seconds: 30
    market_data_timeout_seconds: 10
application:
  logging:
    backup_count: 5
    file: enhanced_trading.log
    level: INFO
    max_size_mb: 100
  risk:
    blue_chip:
      aggressive:
        max_stocks: 5
        position_limit: 0.25
        stop_loss: 0.15
      conservative:
        max_stocks: 8
        position_limit: 0.15
        stop_loss: 0.1
      moderate:
        max_stocks: 6
        position_limit: 0.2
        stop_loss: 0.12
    default_tolerance: moderate
    max_position_size: 0.1
    micro_cap:
      aggressive:
        max_stocks: 8
        position_limit: 0.12
        stop_loss: 0.25
      conservative:
        max_stocks: 15
        position_limit: 0.05
        stop_loss: 0.15
      moderate:
        max_stocks: 12
        position_limit: 0.08
        stop_loss: 0.2
    small_cap:
      aggressive:
        max_stocks: 8
        position_limit: 0.15
        stop_loss: 0.18
      conservative:
        max_stocks: 12
        position_limit: 0.08
        stop_loss: 0.12
      moderate:
        max_stocks: 10
        position_limit: 0.1
        stop_loss: 0.15
backup:
  enabled: true
  frequency_hours: 24
  include_csv: true
  include_database: true
  retention_days: 30
data:
  automation_dir: automation_data
  base_dir: data
  blue_chip_dir: data_blue_chip
  micro_cap_dir: data_micro_cap
  small_cap_dir: data_small_cap
database:
  blue_chip:
    database: stock_market_micro_cap_trading
    description: Blue-chip focused trading database
  host: fhsws001.ksfraser.com
  legacy:
    database: stock_market_2
    description: Legacy database with historical trading data
  micro_cap:
    database: stock_market_micro_cap_trading
    description: Modern per-symbol table structure for micro-cap trading
  password: stocks
  pool:
    max_connections: 10
    pool_name: trading_pool
    pool_reset_session: true
  port: 3306
  username: stocks
